myproject/chat/urls.py
from django.urls import path
from . import views

app_name = "chat"

urlpatterns = [
    path('getMessages/<str:room>/', views.getMessages, name='getMessages'),
    path('', views.home, name='home'),
    path('<str:room>/', views.room, name='room'),
    path('checkview', views.checkview, name='checkview'),
    path('send', views.send, name='send'),
]

myproject/eshop/urls.py
from django.urls.conf import path
from . import views

app_name = "eshop"

urlpatterns = [
    path('', views.eshop, name="eshop"),
    path('login/', views.login_user, name='login'),
    path('customer_user/', views.customer_user, name='customer_user'),

    path('logout/', views.logout, name='logout'),
    path('cart/', views.cart, name='cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('update_item/', views.updateItem, name="update_item"),
    path('process_order/', views.processOrder, name="process_order"),
    path('<int:id>/', views.view_product, name='view_product'),
    path('customer_user/<int:id>/', views.view_product_log, name='view_product_log'),
    path('customer_registration/', views.customer_registration,
         name='customer_registration'),
    path('search/', views.search, name='search'),

    path('mens_hoodies_list_base_page/', views.mens_hoodies_list_base_page, name='mens_hoodies_list_base_page'),
    path('mens_tshirt_list_base_page/', views.mens_tshirt_list_base_page, name='mens_tshirt_list_base_page'),
    path('mens_jean_list_base_page/', views.mens_jean_list_base_page, name='mens_jean_list_base_page'),
    path('mens_coat_list_base_page/', views.mens_coat_list_base_page, name='mens_coat_list_base_page'),

    path('women_hoodies_list_base_page/', views.women_hoodies_list_base_page, name='women_hoodies_list_base_page'),
    path('women_tshirt_list_base_page/', views.women_tshirt_list_base_page, name='women_tshirt_list_base_page'),
    path('women_jean_list_base_page/', views.women_jean_list_base_page, name='women_jean_list_base_page'),
    path('women_coat_list_base_page/', views.women_coat_list_base_page, name='women_coat_list_base_page'),

    path('mens_hoodies_list/', views.mens_hoodies_list, name='mens_hoodies_list'),
    path('mens_tshirt_list/', views.mens_tshirt_list, name='mens_tshirt_list'),
    path('mens_jean_list/', views.mens_jean_list, name='mens_jean_list'),
    path('mens_coat_list/', views.mens_coat_list, name='mens_coat_list'),

    path('women_hoodies_list/', views.women_hoodies_list, name='women_hoodies_list'),
    path('women_tshirt_list/', views.women_tshirt_list, name='women_tshirt_list'),
    path('women_jean_list/', views.women_jean_list, name='women_jean_list'),
    path('women_coat_list/', views.women_coat_list, name='women_coat_list'),

]

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('eshop.urls', namespace='eshop')),
    path('admin/', admin.site.urls),
    path('eshop/', include('eshop.urls', namespace='eshop')),
    path('chat/', include('chat.urls', namespace='chat')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/eshop/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.deletion import CASCADE
from django.core.validators import MinValueValidator, MaxValueValidator


# Create your models here.

# Customer details
class Customer(models.Model):
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200)

    def __str__(self):
        return self.name


# Product details
class Product(models.Model):
    type = models.CharField(max_length=200)
    brand = models.CharField(max_length=200, null=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    size = models.CharField(max_length=50)
    color = models.CharField(max_length=100, null=True)
    sex = models.CharField(max_length=200, null=True)
    image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.type

    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url


# Order details
class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False)
    transaction_id = models.CharField(max_length=100, null=True)

    def __str__(self):
        return str(self.id)

    @property
    def shipping(self):
        shipping = False
        orderitems = self.orderitem_set.all()
        for i in orderitems:
            # if i.product.digital == False:
            shipping = True
        return shipping

    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total

    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total


# Cart details in connection with orders
class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total


# Customer shipping details
class ShippingAddress(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    address = models.CharField(max_length=200, null=False)
    city = models.CharField(max_length=200, null=False)
    state = models.CharField(max_length=200, null=False)
    zipcode = models.CharField(max_length=200, null=False)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.address

myproject/eshop/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import widgets


# Sign up form (with this form we create customers)
class UserCustomerForm(UserCreationForm):
    name = forms.CharField()
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name',
                  'password1', 'password2'

                  )

myproject/eshop/views.py
from django.core.mail import message, send_mail
from django.http import JsonResponse
import json
import datetime
from .models import *
from .utils import cookieCart, cartData, guestOrder
from django.http.response import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.views.decorators.csrf import csrf_exempt, csrf_protect  # Add this
from django.contrib.auth.decorators import login_required
from .forms import UserCustomerForm
from django.core.paginator import Paginator
from django.db.models import Q


# Search
def search(request):
    query = request.GET.get('query', '')
    data = cartData(request)
    cartItems = data['cartItems']
    products = Product.objects.filter(
        Q(type__icontains=query) | Q(brand__icontains=query) | Q(price__icontains=query) | Q(
            color__icontains=query) | Q(sex__icontains=query))
    return render(request, 'eshop/customer_user.html', {'products': products, 'query': query, 'cartItems': cartItems})


# Eshop-Products list-Pagination
def eshop(request):
    products_list = Product.objects.all()
    # Set up Pagination
    p = Paginator(Product.objects.all(), 6)

    page = request.GET.get('page')
    products = p.get_page(page)
    nums = "a" * products.paginator.num_pages

    context = {'products': products, 'products_list': products_list, 'page': page, 'nums': nums}
    return render(request, 'eshop/eshop.html', context)


# User login
@csrf_exempt
def login_user(request):
    errors = {}
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('eshop:customer_user')
        else:
            if not username:
                errors['empty_username'] = 'Please enter username'
            elif not password:
                errors['empty_password'] = 'Please enter password'
            elif user is None:
                errors['invalid'] = 'Username and password do not match'

    return render(request, 'eshop/login.html', errors)


# User Logout
def logout(request):
    return render(request, 'eshop/logout.html', {})


# Customer products, additions to cart
@login_required(login_url='/eshop/login/')
def customer_user(request):
    data = cartData(request)
    cartItems = data['cartItems']

    products_list = Product.objects.all()
    # Set up Pagination
    p = Paginator(Product.objects.all(), 6)

    page = request.GET.get('page')
    products = p.get_page(page)
    nums = "a" * products.paginator.num_pages

    context = {'products': products, 'cartItems': cartItems, 'products_list': products_list, 'page': page, 'nums': nums}
    return render(request, 'eshop/customer_user.html', context)


# Cart
@login_required(login_url='/eshop/login/')
def cart(request):
    data = cartData(request)
    cartItems = data['cartItems']
    order = data['order']
    items = data['items']
    context = {'items': items, 'order': order, 'cartItems': cartItems}
    return render(request, 'eshop/cart.html', context)


# Checkout
@login_required(login_url='/eshop/login/')
def checkout(request):
    data = cartData(request)
    cartItems = data['cartItems']
    order = data['order']
    items = data['items']
    context = {'items': items, 'order': order, 'cartItems': cartItems}
    return render(request, 'eshop/checkout.html', context)


# Update item from cart
def updateItem(request):
    data = json.loads(request.body)
    productId = data['productId']
    action = data['action']
    print('Action:', action)
    print('Product:', productId)
    customer = request.user.customer
    product = Product.objects.get(id=productId)
    order, created = Order.objects.get_or_create(customer=customer, complete=False)
    orderItem, created = OrderItem.objects.get_or_create(order=order, product=product)
    if action == 'add':
        orderItem.quantity = (orderItem.quantity + 1)
    elif action == 'remove':
        orderItem.quantity = (orderItem.quantity - 1)
    orderItem.save()

    if orderItem.quantity <= 0:
        orderItem.delete()
    return JsonResponse('Item was added', safe=False)


# Transaction-Payment
def processOrder(request):
    transaction_id = datetime.datetime.now().timestamp()
    data = json.loads(request.body)
    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
    else:
        customer, order = guestOrder(request, data)
    total = float(data['form']['total'])
    order.transaction_id = transaction_id
    if total == order.get_cart_total:
        order.complete = True
    order.save()

    if order.shipping == True:
        ShippingAddress.objects.create(
            customer=customer,
            order=order,
            address=data['shipping']['address'],
            city=data['shipping']['city'],
            state=data['shipping']['state'],
            zipcode=data['shipping']['zipcode'],
        )
    return JsonResponse('Payment complete', safe=False)


# view product(eshop.html)
def view_product(request, id):
    product_object = Product.objects.get(id=id)
    return render(request, 'eshop/view_product.html', {'product_object': product_object})


# view product for customer(customer_user.html)
@login_required(login_url='/eshop/login/')
def view_product_log(request, id):
    data = cartData(request)
    cartItems = data['cartItems']
    product = Product.objects.get(id=id)
    context = {'product': product, 'cartItems': cartItems}
    return render(request, 'eshop/view_product_log.html', context)


# Customer Sign Up in connection with forms.py
def customer_registration(request):
    customer_form = UserCustomerForm(request.POST)
    if customer_form.is_valid():
        customer_form.save()
        email = customer_form.cleaned_data.get('email')
        name = customer_form.cleaned_data.get('name')
        username = customer_form.cleaned_data.get('username')
        password = customer_form.cleaned_data.get('password1')
        user = User.objects.get(username=username)
        customer = Customer(user=user, email=email, name=name)
        customer.save()
        user = authenticate(request, username=username, password=password)
        login(request, user)
        return HttpResponseRedirect('/eshop/login')
    else:
        customer_form = UserCustomerForm()

    return render(request,
                  'eshop/customer_registration.html', {'form': customer_form})


# Filters(Mens-Womens) for eshop.html
# This function is a filter and choose (Hoodies-Male) products
def mens_hoodies_list_base_page(request):
    products = Product.objects.filter(type='Hoodies', sex='Male')
    context = {'products': products}
    return render(request, 'eshop/eshop.html', context)


# This function is a filter and choose (Tshirt-Male) products
def mens_tshirt_list_base_page(request):
    products = Product.objects.filter(type='Tshirt', sex='Male')
    context = {'products': products}
    return render(request, 'eshop/eshop.html', context)


# This function is a filter and choose (Jean-Male) products
def mens_jean_list_base_page(request):
    products = Product.objects.filter(type='Jean', sex='Male')
    context = {'products': products}
    return render(request, 'eshop/eshop.html', context)


# This function is a filter and choose (Coat-Male) products
def mens_coat_list_base_page(request):
    products = Product.objects.filter(type='Coat', sex='Male')
    context = {'products': products}
    return render(request, 'eshop/eshop.html', context)


# This function is a filter and choose (Hoodies-Women) products
def women_hoodies_list_base_page(request):
    products = Product.objects.filter(type='Hoodies', sex='Women')
    context = {'products': products}
    return render(request, 'eshop/eshop.html', context)


# This function is a filter and choose (Tshirt-Women) products
def women_tshirt_list_base_page(request):
    products = Product.objects.filter(type='Tshirt', sex='Women')
    context = {'products': products}
    return render(request, 'eshop/eshop.html', context)


# This function is a filter and choose (Jean-Women)products
def women_jean_list_base_page(request):
    products = Product.objects.filter(type='Jean', sex='Women')
    context = {'products': products}
    return render(request, 'eshop/eshop.html', context)


# This function is a filter and choose (Coat-Women)products
def women_coat_list_base_page(request):
    products = Product.objects.filter(type='Coat', sex='Women')
    context = {'products': products, }
    return render(request, 'eshop/eshop.html', context)


# Filters(Mens-Womens) for customer.html
# This function is a filter and choose (Hoodies-Male) products
@login_required(login_url='/eshop/login/')
def mens_hoodies_list(request):
    data = cartData(request)

    cartItems = data['cartItems']
    products = Product.objects.filter(type='Hoodies', sex='Male')
    context = {'products': products, 'cartItems': cartItems}
    return render(request, 'eshop/customer_user.html', context)


# This function is a filter and choose (Tshirt-Male) products
@login_required(login_url='/eshop/login/')
def mens_tshirt_list(request):
    data = cartData(request)

    cartItems = data['cartItems']
    products = Product.objects.filter(type='Tshirt', sex='Male')
    context = {'products': products, 'cartItems': cartItems}
    return render(request, 'eshop/customer_user.html', context)


# This function is a filter and choose (Jean-Male) products
@login_required(login_url='/eshop/login/')
def mens_jean_list(request):
    data = cartData(request)
    cartItems = data['cartItems']
    products = Product.objects.filter(type='Jean', sex='Male')

myproject/eshop/templates/eshop/customer_registration.html
{% extends 'eshop/eshop.html' %}


{% block title %}
Регистрация Клиента
{% endblock title %}

{% block content %}
<form method='POST'>
    {% csrf_token %}
    <h2>Регистрация клиента</h2>
    <hr class="mt-0 mb-4">
    {{ form.as_p }} <br>
    <button type="submit" class="btn btn-primary"> Зарегистрироваться </button>
</form>
{% endblock content %}

myproject/eshop/templates/eshop/login.html
{% extends 'eshop/eshop.html' %}
{% block title %}Вход{% endblock%}

<!--Login form-->
{% block linkbar %}
<a href="/eshop/customer_registration/" class="btn btn-warning">Зарегистрироваться</a>
{% endblock%}

{% block content %}
<h1>Вход</h1>
<form method="post">
    {% csrf_token %}

    <label for="username">Имя пользователя:</label>
    <input type="text" id="username" name="username"/> <br>

    <label for="password">Пароль:</label>
    <input type="password" id="password" name="password"/> <br>
    <br>
    {% if empty_username %}
    <div>{{ empty_username }}</div>
    {% elif empty_password %}
    <div>{{ empty_password }}</div>
    {% elif invalid %}
    <div>{{ invalid }}</div>
    {% endif %}
    <br>
    <button type="submit">Войти</button>
</form>
{% endblock%}

myproject/eshop/templates/eshop/main.html
<!DOCTYPE html>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
<html>
<head>
    <title>Fors</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1"/>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script type="text/javascript">
        var user = '{{request.user}}'

        function getToken(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }

        var csrftoken = getToken('csrftoken')

        function getCookie(name) {
            // Split cookie string and get all individual name=value pairs in an array
            var cookieArr = document.cookie.split(";");

            // Loop through the array elements
            for (var i = 0; i < cookieArr.length; i++) {
                var cookiePair = cookieArr[i].split("=");

                /* Removing whitespace at the beginning of the cookie name
                and compare it with the given string */
                if (name == cookiePair[0].trim()) {
                    // Decode the cookie value and return
                    return decodeURIComponent(cookiePair[1]);
                }
            }
            // Return null if not found
            return null;
        }

        var cart = JSON.parse(getCookie('cart'))

        if (cart == undefined) {
            cart = {}
            console.log('Cart Created!', cart)
            document.cookie = 'cart=' + JSON.stringify(cart) + ";domain=;path=/"
        }
        console.log('Cart:', cart)

    </script>
    <style>
        /* Button used to open the chat form - fixed at the bottom of the page */
        .open-button {
            background-color: white;
            color: white;
            padding: 20px 20px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            opacity: 0.8;
            position: fixed;
            bottom: 23px;
            right: 28px;
            width: 80px;
        }

        .open-button:hover {
            background-color: #a7a7a1;
            outline: none;
        }

        .fa {
            padding: 20px;
            font-size: 30px;
            width: 50px;
            text-align: center;
            text-decoration: none;
            margin: 5px 2px;
            border-radius: 50%;
        }

        .fa:hover {
            opacity: 0.7;
        }

        .fa-facebook {
            background: #3B5998;
            color: white;
        }

        .fa-twitter {
            background: #55ACEE;
            color: white;
        }

        .fa-instagram {
            background: #125688;
            color: white;
        }

        .small-btn {
            width: 0px;
            height: 0px;
        }
    </style>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
<!--Navbar-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'eshop:customer_user' %}">
        <img src="{% static  'images/logo.pn' %}" alt="Logo" style="width:60px;">
    </a>


    <div class="collapse navbar-collapse" id="navbarSupportedContent">


        <!--Men filters and buttons-->
        <ul class="nav nav-pills">
            <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">
                    Мужское
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <a href="/eshop/mens_tshirt_list/" class="dropdown-item">Футболки </a>
                    <hr>
                    <a href="/eshop/mens_hoodies_list/" class="dropdown-item">Худи </a>
                    <hr>
                    <a href="/eshop/mens_jean_list/" class="dropdown-item">Джинсы</a>
                    <hr>
                    <a href="/eshop/mens_coat_list/" class="dropdown-item">Пальто</a>
                </div>
            </div>
        </ul>
        <!--Women filters and buttons-->
        <ul class="nav nav-pills mr-auto">
            <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Женское
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <a href="/eshop/women_tshirt_list/" class="dropdown-item">Футболки </a>
                    <hr>
                    <a href="/eshop/women_hoodies_list/" class="dropdown-item">Худи </a>
                    <hr>
                    <a href="/eshop/women_jean_list/" class="dropdown-item">Джинсы</a>
                    <hr>
                    <a href="/eshop/women_coat_list/" class="dropdown-item">Пальто</a>
                </div>
            </div>
        </ul>


        <!--Search filter and button-->
        <ul>
            <div class="navbar-menu" id="main-navbar">
                <div class="navbar-start" style="margin-right:-100px;margin-left:300px;">
                    <div class="navbar-item">
                        <form id="search" method="get" action="{% url 'eshop:search' %}">
                            <div class="field has-addons">
                                <div class="control">
                                    <input id="search-focus" type="text" class="input1" placeholder="Бренд, Цвет, Цена"
                                           name="query">
                                    <button class="button small" type="submit">Поиск</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </ul>
        <!--Chat button-->
        <form action="{% url 'chat:home' %}" target="_blank">
            <input class="open-button" type="image"
                   src="https://upload.wikimedia.org/wikipedia/commons/4/4c/Nuvola_apps_chat.svg"/>
        </form>
        <div class="form-inline my-2 my-lg-0">
            <a href="{% url 'eshop:cart' %}">
                <img id="cart-icon" src="{% static 'images/cart.png' %}">
            </a>
            <p id="cart-total">{{cartItems}}</p>
            <a href="/eshop/logout/" class="btn btn-danger">Выйти</a>
        </div>


    </div>
</nav>

<div class="container">
    <br>
    {% block content %}


    {% endblock content %}
</div>
<br><br>

<!--Navbar for pagination-->
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
        <li class="page-item disabled">

            {% if products.has_previous %}
        <li class="page-item"><a class="page-link" href="?page=1">&laquo Первый</a></li>
        <li class="page-item"><a class="page-link" href="?page={{ products.previous_page_number }}">Предыдущий</a>
        </li>
        {% endif %}

        {% for i in nums %}
        <li class="page-item"><a class="page-link"
                                 href="?page={{ forloop.counter }}">{{forloop.counter}}</a></li>

        {% endfor %}

        {% if products.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ products.next_page_number }}">Далее</a></li>
        <li class="page-item"><a class="page-link"
                                 href="?page={{ products.paginator.num_pages }}">Последний&raquo</a></li>
        {% endif %}
        </li>
    </ul>
</nav>
<footer class="bg-white">
    <div class="container py-5">
        <div class="row py-4">

            <div class="col-lg-3 col-md-6 mb-4 mb-lg-0">
                <h6 class="text-uppercase font-weight-bold mb-4">Fors</h6>
                <ul class="list-unstyled mb-0">
                    <li class="mb-2"><a href="{% url 'eshop:eshop' %}" class="text-muted">Вся продукция</a></li>
                    <li class="mb-2"><a href="{% url 'eshop:eshop' %}" class="text-muted">Адресса магазинов</a></li>
                    <li class="mb-2"><a href="mailto:Fors@fors.com" class="text-muted">Связаться по почте</a></li>
                </ul>

            </div>
            <div class="col-lg-3 col-md-6 mb-4 mb-lg-0">
                <h6 class="text-uppercase font-weight-bold mb-4">Ип</h6>
                <ul class="list-unstyled mb-0">
                    <li class="mb-2"><a href="/" target="_blank" class="text-muted">Правовые сведение об ИП Сохибов
                        Ф.О. </a></li>
                    <li class="mb-2"><a href="/" target="_blank" class="text-muted">Сфера деятельности</a></li>
                    <li class="mb-2"><a href="/" target="_blank" class="text-muted">Сведение из ЕГРИП</a></li>
                </ul>

            </div>
            <div class="col-lg-3 col-md-6 mb-lg-0">
                <h6 class="text-uppercase font-weight-bold mb-4">О нас</h6>
                <p class="text-muted mb-4">Наши магазины работают с 2000 года. В настоящее время они занимают лидирующие
                    позиции на рынке, сохраняя высокие темпы роста внутри страны.</p>

            </div>
            <div class="col-lg-3 col-md-6 mb-lg-4">
					  <h6 class="text-uppercase font-weight-bold mb-4">Мы в соц сетях</h6>
                        <li href="mel:83432967981" class="text-muted">Tel: 83432967981</li>
						<li class="list-inline-item"><a href="https://Vk.ru/ali_soibov/" class="fa fa-facebook" target="_blank" ></i></a></li>
						<li class="list-inline-item"><a href="https://www.instagram.com/ali_soibov" class="fa fa-instagram" target="_blank"></i></a></li>
						<li class="list-inline-item"><a href="https://telegramm.com/ali_soibov/?lang=el" class="fa fa-twitter" target="_blank"></a></i></li>
					</div>
				  </div>
            </div>

                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2117.851851440877!2d60.011364516260585!3d57.939522681194234!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x43ea6356634519ef%3A0x7c91c3c8a2f82cb8!2z0KTQvtGA0YE!5e0!3m2!1sru!2sru!4v1669234533840!5m2!1sru!2sru" width="430" height="300" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
				<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d4316.189763014478!2d60.10395908006652!3d57.2550364739267!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x43c191514700850b%3A0x718fdb1f8289d266!2z0KTQntCg0KEg0L7QtNC10LbQtNCwINC-0LHRg9Cy0Yw!5e0!3m2!1sru!2sru!4v1669234657460!5m2!1sru!2sru" width="430" height="300" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>

    </div>

</footer>

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>

<script type="text/javascript" src="{% static 'js/cart.js' %}"></script>
</body>


</html>